name: karuta
base: core18
version: '0.6.3wip'
summary: Karuta is a scripting language for FPGA design (so called HLS).
description: |
  Karuta is an object-oriented scripting language and its compiler to design logic circuits. The main objective of Karuta is to improve the productivity of logic circuit design. This kind of software is usually known as HLS (High Level Synthesis).

grade: stable
confinement: strict
base: core18

parts:
  karuta:
    plugin: dump
    source: pkg.tar.gz # make pkg

apps:
  karuta:
    command: karuta
    plugs:
      - home
